export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED';

export const USER_ANSWERS_CLEAR = 'USER_ANSWERS_CLEAR'; 
export const USER_ANSWERS_ADD_CORRECT_ANSWER = 'USER_ANSWERS_ADD_CORRECT_ANSWER'; 
export const USER_ANSWERS_ADD_WRONG_ANSWER = 'USER_ANSWERS_ADD_WRONG_ANSWER'; 
